version: '3.8'

services:
  flask:
    build: .
    # ports:
    #   - "5000:5000"
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask
    restart: unless-stopped
