version: '3.8'

services:
  flask:
    build: .
    # ports:
    #   - "5000:5000"
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-lb.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
    restart: unless-stopped
