# filename: prometheus-config-pod-sd.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'node-exporter-pods'
        kubernetes_sd_configs:
          - role: pod
            kubeconfig_file: ""
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: monitoring
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: node-exporter
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: 9100
          - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_container_port_number]
            separator: ':'
            target_label: __address__
            action: replace
---
# Prometheus 배포
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:v2.55.0
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.enable-admin-api
          ports:
            - name: web
              containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: data
          emptyDir: {}
---
# Grafana 데이터소스/대시보드 설정
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: 'Node Exporter'
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards
  node_exporter_full.json: |
    {
      "__inputs": [],
      "__requires": [],
      "title": "Node Exporter Quick View",
      "timezone": "",
      "schemaVersion": 38,
      "version": 1,
      "refresh": "30s",
      "panels": [
        {
          "type": "graph",
          "title": "CPU usage (node)",
          "targets": [
            { "expr": "100 - (avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)", "legendFormat": "{{instance}}" }
          ]
        },
        {
          "type": "graph",
          "title": "Memory usage (node)",
          "targets": [
            { "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100", "legendFormat": "{{instance}}" }
          ]
        },
        {
          "type": "graph",
          "title": "Load average (1m)",
          "targets": [
            { "expr": "node_load1", "legendFormat": "{{instance}}" }
          ]
        },
        {
          "type": "graph",
          "title": "Disk read/write bytes",
          "targets": [
            { "expr": "sum by(instance)(rate(node_disk_read_bytes_total[5m]))", "legendFormat": "read {{instance}}" },
            { "expr": "sum by(instance)(rate(node_disk_written_bytes_total[5m]))", "legendFormat": "write {{instance}}" }
          ]
        },
        {
          "type": "graph",
          "title": "Network rx/tx bytes",
          "targets": [
            { "expr": "sum by(instance)(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m]))", "legendFormat": "rx {{instance}}" },
            { "expr": "sum by(instance)(rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m]))", "legendFormat": "tx {{instance}}" }
          ]
        }
      ]
    }
---
# Grafana 배포
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:12.4.0-19274378403
          ports:
            - name: web
              containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/datasources/datasources.yml
              subPath: datasources.yml
            - name: grafana-config-dash
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yml
              subPath: dashboards.yml
            - name: grafana-dash-jsons
              mountPath: /var/lib/grafana/dashboards/node_exporter_full.json
              subPath: node_exporter_full.json
            - name: grafana-storage
              mountPath: /var/lib/grafana
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: grafana-config-dash
          configMap:
            name: grafana-config
        - name: grafana-dash-jsons
          configMap:
            name: grafana-config
        - name: grafana-storage
          emptyDir: {}
