# 서비스 생성
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
  selector:
    app: node-exporter
---
# node-exporter 서비스 (Prometheus가 접근)
apiVersion: v1
kind: Service
metadata:
  name: node-exporter-nodeport
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  type: NodePort
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
      nodePort: 30100
  selector:
    app: node-exporter