apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  selector:
    app: nginx
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30007  # 30000-32767 범위에서 지정
  type: NodePort
